version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5180:5180"
    env_file:
      - .env.production
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    env_file:
      - .env.production
    depends_on:
      - backend
    restart: always
