version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5180:5180"
    env_file:
      - .env.${ENV:-development}
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env.${ENV:-development}
    depends_on:
      - backend
    restart: always
