version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5180:5180"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
